# Generated by Django 6.1 on 2026-08-20 12:38

from decimal import Decimal

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anagrafica", "0002_alter_censimentocapo_branca_and_more"),
        ("organizzazione", "0002_seed_e9001"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TipologiaCampo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("codice", models.CharField(max_length=20, unique=True)),
                ("nome", models.CharField(max_length=150)),
                ("approvazione_automatica", models.BooleanField(default=False)),
                (
                    "quota_default",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "livello",
                    models.CharField(
                        choices=[
                            ("ZONA", "Zona"),
                            ("REG", "Regionale"),
                            ("NAZ", "Nazionale"),
                            ("ALTRO", "Altro"),
                        ],
                        max_length=10,
                    ),
                ),
                ("attiva", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tipologia campo",
                "verbose_name_plural": "Tipologie campo",
                "ordering": ["codice"],
            },
        ),
        migrations.CreateModel(
            name="Campagna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("anno", models.IntegerField(unique=True)),
                ("budget", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tetto_per_partecipazione",
                    models.DecimalField(decimal_places=2, default=Decimal("50.00"), max_digits=10),
                ),
                ("data_inizio_inserimento", models.DateField()),
                ("data_fine_inserimento", models.DateField()),
                (
                    "stato",
                    django_fsm.FSMField(
                        choices=[
                            ("APERTA", "Aperta"),
                            ("IN_VALUTAZIONE", "In valutazione"),
                            ("CHIUSA", "Chiusa"),
                            ("LIQUIDATA", "Liquidata"),
                        ],
                        default="APERTA",
                        max_length=50,
                        protected=True,
                    ),
                ),
                ("chiusa_il", models.DateTimeField(blank=True, null=True)),
                ("liquidata_il", models.DateTimeField(blank=True, null=True)),
                ("riferimento_bonifico", models.CharField(blank=True, max_length=100)),
                (
                    "creata_da",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campagne_create",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Campagna",
                "verbose_name_plural": "Campagne",
                "ordering": ["-anno"],
            },
        ),
        migrations.CreateModel(
            name="ImportazionePartecipazioni",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file", models.FileField(upload_to="import_partecipazioni/%Y/")),
                ("conteggi", models.JSONField(default=dict)),
                ("anomalie", models.JSONField(default=list)),
                ("eseguita_il", models.DateTimeField(auto_now_add=True)),
                (
                    "campagna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="importazioni_partecipazioni",
                        to="contributi.campagna",
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="importazioni_partecipazioni",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Importazione partecipazioni",
                "verbose_name_plural": "Importazioni partecipazioni",
                "ordering": ["-eseguita_il"],
            },
        ),
        migrations.CreateModel(
            name="Partecipazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("descrizione_altro", models.CharField(blank=True, max_length=200)),
                ("data_inizio", models.DateField()),
                ("data_fine", models.DateField()),
                ("luogo", models.CharField(max_length=200)),
                ("quota_versata", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "stato",
                    django_fsm.FSMField(
                        choices=[
                            ("INSERITA", "Inserita"),
                            ("APPROVATA", "Approvata"),
                            ("RESPINTA", "Respinta"),
                            ("DOCUMENTI_RICHIESTI", "Documenti richiesti"),
                        ],
                        default="INSERITA",
                        max_length=50,
                        protected=True,
                    ),
                ),
                ("motivazione_respingimento", models.TextField(blank=True)),
                ("data_valutazione", models.DateTimeField(blank=True, null=True)),
                (
                    "campagna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partecipazioni",
                        to="contributi.campagna",
                    ),
                ),
                (
                    "capo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partecipazioni",
                        to="anagrafica.capo",
                    ),
                ),
                (
                    "gruppo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partecipazioni",
                        to="organizzazione.gruppo",
                    ),
                ),
                (
                    "inserita_da",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partecipazioni_inserite",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "valutata_da",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partecipazioni_valutate",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipologia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partecipazioni",
                        to="contributi.tipologiacampo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partecipazione",
                "verbose_name_plural": "Partecipazioni",
                "ordering": ["-campagna_id", "capo"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("campagna", "capo", "tipologia", "data_inizio"),
                        name="uniq_partecipazione_chiave_logica",
                    )
                ],
            },
        ),
    ]
