# Generated by Django 6.1 on 2026-08-20 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributi", "0002_seed_tipologie"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AllegatoPartecipazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file", models.FileField(upload_to="allegati_partecipazioni/%Y/")),
                ("tipo", models.CharField(blank=True, max_length=100)),
                ("caricato_il", models.DateTimeField(auto_now_add=True)),
                (
                    "caricato_da",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allegati_partecipazioni_caricati",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partecipazione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allegati",
                        to="contributi.partecipazione",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allegato partecipazione",
                "verbose_name_plural": "Allegati partecipazione",
                "ordering": ["-caricato_il"],
            },
        ),
        migrations.CreateModel(
            name="ContributoPartecipazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("importo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_simulazione", models.BooleanField()),
                ("calcolato_il", models.DateTimeField(auto_now_add=True)),
                (
                    "partecipazione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contributi",
                        to="contributi.partecipazione",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contributo partecipazione",
                "verbose_name_plural": "Contributi partecipazione",
                "ordering": ["-calcolato_il"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("partecipazione", "is_simulazione"),
                        name="uniq_contributo_partecipazione_simulazione",
                    )
                ],
            },
        ),
    ]
