# Generated by Django 6.1 on 2026-08-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributi", "0004_seed_tipologia_altro"),
    ]

    operations = [
        migrations.AddField(
            model_name="partecipazione",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="partecipazione",
            name="luogo",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
