# Generated by Django 6.1 on 2026-09-13 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributi", "0005_partecipazione_note_alter_partecipazione_luogo"),
        ("organizzazione", "0005_alter_gruppo_account_consentiti_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DichiarazioneNessunRimborso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dichiarata_il", models.DateTimeField(auto_now_add=True)),
                (
                    "campagna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dichiarazioni_nessun_rimborso",
                        to="contributi.campagna",
                    ),
                ),
                (
                    "dichiarata_da",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dichiarazioni_nessun_rimborso",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gruppo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dichiarazioni_nessun_rimborso",
                        to="organizzazione.gruppo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dichiarazione nessun rimborso",
                "verbose_name_plural": "Dichiarazioni nessun rimborso",
                "ordering": ["-dichiarata_il"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("campagna", "gruppo"), name="uniq_dichiarazione_nessun_rimborso"
                    )
                ],
            },
        ),
    ]
