# Generated by Django 6.1 on 2026-08-20 08:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("attiva", models.BooleanField(default=True)),
                ("data_inizio", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "data_fine",
                    models.DateField(help_text="Obbligatoria, a differenza del ruolo (D-04)."),
                ),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Delega",
                "verbose_name_plural": "Deleghe",
                "ordering": ["-data_inizio"],
            },
        ),
        migrations.CreateModel(
            name="InvitoAttivazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "ruolo_proposto",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ADMIN", "Amministratore"),
                            ("SEGRETERIA", "Segreteria"),
                            ("RDZ", "Responsabile di Zona"),
                            ("AEZ", "Assistente Ecclesiastico di Zona"),
                            ("MCZ", "Membro Comitato di Zona"),
                            ("CG", "Capogruppo"),
                            ("IABZ", "Incaricato alla Branca di Zona"),
                            ("ISZ", "Incaricato ai Settori di Zona"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("codice_hash", models.CharField(max_length=128)),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("INVIATO", "Inviato"),
                            ("USATO", "Usato"),
                            ("SCADUTO", "Scaduto"),
                            ("REVOCATO", "Revocato"),
                        ],
                        default="INVIATO",
                        max_length=10,
                    ),
                ),
                ("scadenza", models.DateTimeField(default=apps.accounts.models._scadenza_default)),
                ("tentativi", models.PositiveSmallIntegerField(default=0)),
                ("inviato_il", models.DateTimeField(blank=True, null=True)),
                ("usato_il", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Invito di attivazione",
                "verbose_name_plural": "Inviti di attivazione",
                "ordering": ["-inviato_il"],
            },
        ),
        migrations.CreateModel(
            name="Ruolo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Amministratore"),
                            ("SEGRETERIA", "Segreteria"),
                            ("RDZ", "Responsabile di Zona"),
                            ("AEZ", "Assistente Ecclesiastico di Zona"),
                            ("MCZ", "Membro Comitato di Zona"),
                            ("CG", "Capogruppo"),
                            ("IABZ", "Incaricato alla Branca di Zona"),
                            ("ISZ", "Incaricato ai Settori di Zona"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "branca",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LC", "Lupetti/Coccinelle"),
                            ("EG", "Esploratori/Guide"),
                            ("RS", "Rover/Scolte"),
                        ],
                        max_length=5,
                    ),
                ),
                ("settore", models.CharField(blank=True, max_length=100)),
                ("attivo", models.BooleanField(default=True)),
                ("data_inizio", models.DateField(default=django.utils.timezone.localdate)),
                ("data_fine", models.DateField(blank=True, null=True)),
                (
                    "origine",
                    models.CharField(
                        choices=[
                            ("DERIVATO", "Derivato dall'incarico (D-30)"),
                            ("AMMINISTRATIVO", "Amministrativo"),
                        ],
                        default="AMMINISTRATIVO",
                        max_length=15,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ruolo",
                "verbose_name_plural": "Ruoli",
                "ordering": ["utente", "tipo"],
            },
        ),
        migrations.CreateModel(
            name="SessioneImpersonificazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("iniziata_il", models.DateTimeField(auto_now_add=True)),
                ("terminata_il", models.DateTimeField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Sessione di impersonificazione",
                "verbose_name_plural": "Sessioni di impersonificazione",
                "ordering": ["-iniziata_il"],
            },
        ),
        migrations.CreateModel(
            name="Utente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PERSONA", "Persona"),
                            ("GRUPPO", "Account funzionale di gruppo"),
                        ],
                        default="PERSONA",
                        max_length=10,
                    ),
                ),
                (
                    "codice_socio",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("ATTIVO", "Attivo"),
                            ("IN_ATTESA", "In attesa"),
                            ("SOSPESO", "Sospeso"),
                        ],
                        default="IN_ATTESA",
                        max_length=10,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utente",
                "verbose_name_plural": "Utenti",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
