# Generated by Django 6.1 on 2026-08-20 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("organizzazione", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="utente",
            name="gruppo",
            field=models.ForeignKey(
                blank=True,
                help_text="Identifica solo l'account funzionale, mai il perimetro operativo (D-28/D-33): usare sempre gruppi_visibili().",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="account_funzionali",
                to="organizzazione.gruppo",
            ),
        ),
        migrations.AddField(
            model_name="utente",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="delega",
            name="delegante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deleghe_concesse",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="delega",
            name="delegato",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deleghe_ricevute",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invitoattivazione",
            name="creato_da",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inviti_creati",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invitoattivazione",
            name="delega_pendente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inviti",
                to="accounts.delega",
            ),
        ),
        migrations.AddField(
            model_name="invitoattivazione",
            name="gruppo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inviti_attivazione",
                to="organizzazione.gruppo",
            ),
        ),
        migrations.AddField(
            model_name="ruolo",
            name="assegnato_da",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ruoli_assegnati",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ruolo",
            name="gruppo",
            field=models.ForeignKey(
                blank=True,
                help_text="Obbligatorio solo per il ruolo CG.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ruoli_cg",
                to="organizzazione.gruppo",
            ),
        ),
        migrations.AddField(
            model_name="ruolo",
            name="utente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ruoli",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="delega",
            name="ruolo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deleghe",
                to="accounts.ruolo",
            ),
        ),
        migrations.AddField(
            model_name="sessioneimpersonificazione",
            name="amministratore",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessioni_come_amministratore",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sessioneimpersonificazione",
            name="utente_impersonato",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessioni_subite",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
