# Generated by Django 6.1 on 2026-08-21 08:20

from django.db import migrations

import apps.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="utente",
            managers=[
                ("objects", apps.accounts.models.UtenteManager()),
            ],
        ),
    ]
