# Generated by Django 6.1 on 2026-09-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_utente_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delega",
            name="data_fine",
            field=models.DateField(help_text="Obbligatoria, a differenza del ruolo."),
        ),
        migrations.AlterField(
            model_name="ruolo",
            name="origine",
            field=models.CharField(
                choices=[
                    ("DERIVATO", "Derivato dall'incarico"),
                    ("AMMINISTRATIVO", "Amministrativo"),
                ],
                default="AMMINISTRATIVO",
                max_length=15,
            ),
        ),
    ]
