# Generated by Django 6.1 on 2026-09-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_utente_branca_tema_preferita"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utente",
            name="branca_tema_preferita",
            field=models.CharField(
                blank=True,
                choices=[
                    ("generico", "Generico (azzurro)"),
                    ("generico2", "Generico 2 (viola indaco)"),
                    ("capi", "Capi / Comunità Capi (viola)"),
                    ("lc", "Branco/Cerchio (giallo)"),
                    ("eg", "Reparto (verde)"),
                    ("rs", "Clan/Fuoco (rosso)"),
                ],
                help_text="Vuoto = usa lo schema colori definito per tutta la piattaforma.",
                max_length=10,
                verbose_name="Schema colori preferito",
            ),
        ),
    ]
