# Generated by Django 6.1 on 2026-08-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImpostazioniPiattaforma",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("causale_bonifico_default", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Impostazioni piattaforma",
                "verbose_name_plural": "Impostazioni piattaforma",
            },
        ),
    ]
