# Generated by Django 6.1 on 2026-08-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "codice",
                    models.CharField(
                        choices=[
                            ("invito_attivazione", "Invito di attivazione"),
                            ("fine_impersonificazione", "Fine impersonificazione"),
                            ("delega_creata", "Delega creata"),
                            ("delega_revocata", "Delega revocata"),
                            ("incarico_assegnato", "Incarico assegnato"),
                            ("incarico_cessato", "Incarico cessato"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("oggetto", models.CharField(max_length=200)),
                ("corpo_html", models.TextField(blank=True)),
                ("corpo_testo", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Template email",
                "verbose_name_plural": "Template email",
                "ordering": ["codice"],
            },
        ),
    ]
