# Generated by Django 6.1 on 2026-08-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_seed_template_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="impostazionipiattaforma",
            name="email_su_mailpit",
            field=models.BooleanField(
                default=False,
                help_text="Solo in produzione (apps.core.email.override.MailpitOverridableBackend): reindirizza ogni email verso Mailpit invece di consegnarla davvero. Richiede EMAIL_MAILPIT_HOST configurato.",
                verbose_name="Invia le email su Mailpit invece del provider configurato",
            ),
        ),
    ]
