# Generated by Django 6.1 on 2026-08-31 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_impostazionipiattaforma_email_su_mailpit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImmagineTemplateEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file", models.ImageField(upload_to="template_email_immagini/%Y/")),
                ("caricata_il", models.DateTimeField(auto_now_add=True)),
                (
                    "caricata_da",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Immagine template email",
                "verbose_name_plural": "Immagini template email",
            },
        ),
    ]
