# Generated by Django 6.1 on 2026-09-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_immaginetemplateemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="impostazionipiattaforma",
            name="firma_html",
            field=models.TextField(
                blank=True,
                help_text="Aggiunta in coda al corpo HTML di ogni email inviata tramite template.",
                verbose_name="Firma (HTML)",
            ),
        ),
        migrations.AddField(
            model_name="impostazionipiattaforma",
            name="firma_testo",
            field=models.TextField(
                blank=True,
                help_text="Aggiunta in coda al corpo testuale di ogni email inviata tramite template.",
                verbose_name="Firma (testo)",
            ),
        ),
        migrations.AddField(
            model_name="impostazionipiattaforma",
            name="prefisso_oggetto_email",
            field=models.CharField(
                blank=True,
                help_text="Anteposto automaticamente all'oggetto di ogni email inviata (\"prefisso - oggetto\"). Disponibile anche come {{ subjectPrefix }} nel corpo e nella firma, ma non nell'oggetto del singolo template: ci finirebbe due volte.",
                max_length=50,
                verbose_name="Prefisso oggetto email",
            ),
        ),
    ]
