# Generated by Django 6.1 on 2026-09-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_impostazionipiattaforma_firma_html_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="impostazionipiattaforma",
            name="branca_tema_default",
            field=models.CharField(
                blank=True,
                choices=[
                    ("generico", "Generico (azzurro)"),
                    ("capi", "Capi / Comunità Capi (viola)"),
                    ("lc", "Branco/Cerchio (giallo)"),
                    ("eg", "Reparto (verde)"),
                    ("rs", "Clan/Fuoco (rosso)"),
                ],
                help_text="Vuoto = usa lo schema colori predefinito del tema. Non sovrascrive le preferenze personali già impostate dagli utenti.",
                max_length=10,
                verbose_name="Schema colori di sistema",
            ),
        ),
    ]
