# Generated by Django 6.1 on 2026-09-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_impostazionipiattaforma_branca_tema_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="impostazionipiattaforma",
            name="branca_tema_default",
            field=models.CharField(
                blank=True,
                choices=[
                    ("generico", "Generico (azzurro)"),
                    ("generico2", "Generico 2 (viola indaco)"),
                    ("capi", "Capi / Comunità Capi (viola)"),
                    ("lc", "Branco/Cerchio (giallo)"),
                    ("eg", "Reparto (verde)"),
                    ("rs", "Clan/Fuoco (rosso)"),
                ],
                help_text="Vuoto = usa lo schema colori predefinito del tema. Non sovrascrive le preferenze personali già impostate dagli utenti.",
                max_length=10,
                verbose_name="Schema colori di sistema",
            ),
        ),
    ]
