# Generated by Django 6.1 on 2026-09-09 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_impostazionipiattaforma_branca_tema_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="impostazionipiattaforma",
            name="durata_inattivita_minuti",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Trascorsi questi minuti senza richieste, l'utente autenticato viene disconnesso.",
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(480),
                ],
                verbose_name="Durata inattività prima della scadenza sessione (minuti)",
            ),
        ),
    ]
