# Generated by Django 6.1 on 2026-09-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_impostazionipiattaforma_durata_inattivita_minuti"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templateemail",
            name="codice",
            field=models.CharField(
                choices=[
                    ("invito_attivazione", "Invito di attivazione"),
                    ("fine_impersonificazione", "Fine impersonificazione"),
                    ("delega_creata", "Delega creata"),
                    ("delega_revocata", "Delega revocata"),
                    ("incarico_assegnato", "Incarico assegnato"),
                    ("incarico_cessato", "Incarico cessato"),
                    ("nota_spese_rilievo", "Nota spese — rilievo"),
                    ("nota_spese_approvata", "Nota spese — approvata"),
                    ("nota_spese_respinta", "Nota spese — respinta"),
                    ("nota_spese_liquidata", "Nota spese — liquidata"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
