# Generated by Django 6.1 on 2026-08-20 08:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnoAssociativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("anno", models.IntegerField(unique=True)),
            ],
            options={
                "verbose_name": "Anno associativo",
                "verbose_name_plural": "Anni associativi",
                "ordering": ["-anno"],
            },
        ),
        migrations.CreateModel(
            name="Gruppo",
            fields=[
                (
                    "codice",
                    models.CharField(
                        help_text="Ordinale AGESCI, es. E0133.",
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Il codice ordinale deve avere la forma 'E' seguita da 4 cifre (es. E0133).",
                                regex="^E\\d{4}$",
                            )
                        ],
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "is_comitato_zona",
                    models.BooleanField(
                        default=False,
                        help_text="True solo per E9001: non è una Comunità Capi (D-33).",
                    ),
                ),
                ("email_istituzionale", models.EmailField(blank=True, max_length=254)),
                ("indirizzo", models.CharField(blank=True, max_length=200)),
                ("civico", models.CharField(blank=True, max_length=10)),
                ("cap", models.CharField(blank=True, max_length=10)),
                ("comune", models.CharField(blank=True, max_length=100)),
                ("provincia", models.CharField(blank=True, max_length=5)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("codice_fiscale", models.CharField(blank=True, max_length=20)),
                ("denominazione_sociale", models.CharField(blank=True, max_length=200)),
                ("parrocchia", models.CharField(blank=True, max_length=200)),
                ("diocesi", models.CharField(blank=True, max_length=100)),
                ("iban", models.CharField(blank=True, max_length=34)),
                ("intestazione_conto", models.CharField(blank=True, max_length=200)),
                (
                    "data_autorizzazione",
                    models.DateField(
                        blank=True,
                        help_text="Ultima data_aggiornamento importata dall'autorizzazione (D-09, M3).",
                        null=True,
                    ),
                ),
                (
                    "origine",
                    models.CharField(
                        choices=[("IMPORT", "Import"), ("MANUALE", "Manuale")],
                        default="MANUALE",
                        max_length=10,
                    ),
                ),
                (
                    "account_consentiti",
                    models.PositiveSmallIntegerField(default=1, help_text="E9001 vale 2 (D-33)."),
                ),
            ],
            options={
                "verbose_name": "Gruppo",
                "verbose_name_plural": "Gruppi",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="AllowlistGruppo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("codice_gruppo", models.CharField(max_length=8)),
                ("email", models.EmailField(max_length=254)),
                (
                    "origine",
                    models.CharField(
                        choices=[("IMPORT", "Import"), ("MANUALE", "Manuale")],
                        default="MANUALE",
                        max_length=10,
                    ),
                ),
                ("creata_il", models.DateTimeField(auto_now_add=True)),
                (
                    "creata_da",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allowlist_create",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Allowlist gruppo",
                "verbose_name_plural": "Allowlist gruppi",
                "ordering": ["codice_gruppo", "email"],
                "constraints": [
                    models.UniqueConstraint(fields=("email",), name="uniq_allowlist_email")
                ],
            },
        ),
        migrations.CreateModel(
            name="StatoGruppoAnno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("anno_scout", models.IntegerField()),
                ("attivo", models.BooleanField()),
                ("motivo", models.TextField(blank=True)),
                ("disposto_il", models.DateTimeField(auto_now_add=True)),
                (
                    "disposto_da",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stati_gruppo_disposti",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gruppo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stati_annuali",
                        to="organizzazione.gruppo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stato gruppo per anno",
                "verbose_name_plural": "Stati gruppo per anno",
                "ordering": ["gruppo", "-anno_scout"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("gruppo", "anno_scout"), name="uniq_stato_gruppo_anno"
                    )
                ],
            },
        ),
    ]
