# Generated by Django 6.1 on 2026-08-20 15:33

from django.db import migrations, models

import apps.organizzazione.iban


class Migration(migrations.Migration):

    dependencies = [
        ("organizzazione", "0002_seed_e9001"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gruppo",
            name="iban",
            field=models.CharField(
                blank=True, max_length=34, validators=[apps.organizzazione.iban.valida_iban]
            ),
        ),
    ]
