# Generated by Django 6.1 on 2026-08-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizzazione", "0003_alter_gruppo_iban"),
    ]

    operations = [
        migrations.AddField(
            model_name="gruppo",
            name="email_alternativa",
            field=models.EmailField(
                blank=True,
                help_text="Impostabile dal gruppo (Gestione gruppo): email_istituzionale, da import, non è mai modificabile da quel form.",
                max_length=254,
            ),
        ),
    ]
