# Generated by Django 6.1 on 2026-09-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizzazione", "0004_gruppo_email_alternativa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gruppo",
            name="account_consentiti",
            field=models.PositiveSmallIntegerField(default=1, help_text="E9001 vale 2."),
        ),
        migrations.AlterField(
            model_name="gruppo",
            name="data_autorizzazione",
            field=models.DateField(
                blank=True,
                help_text="Ultima data_aggiornamento importata dall'autorizzazione.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="gruppo",
            name="is_comitato_zona",
            field=models.BooleanField(
                default=False, help_text="True solo per E9001: non è una Comunità Capi."
            ),
        ),
    ]
