# Generated by Django 6.1 on 2026-09-15 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Localita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("provincia", models.CharField(blank=True, max_length=100)),
                (
                    "codice_istat",
                    models.CharField(blank=True, max_length=6, null=True, unique=True),
                ),
                ("estero", models.BooleanField(default=False)),
                ("stato", models.CharField(blank=True, max_length=100)),
                ("latitudine", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitudine", models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                "verbose_name": "Località",
                "verbose_name_plural": "Località",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="CentroCosto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("attivo", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="figli",
                        to="note_spese.centrocosto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Centro di costo",
                "verbose_name_plural": "Centri di costo",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="BudgetCentroCosto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("anno_scout", models.IntegerField()),
                ("importo", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "centro_costo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budget_annuali",
                        to="note_spese.centrocosto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget del centro di costo",
                "verbose_name_plural": "Budget dei centri di costo",
                "ordering": ["-anno_scout", "centro_costo__nome"],
            },
        ),
        migrations.CreateModel(
            name="CategoriaSpesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("richiede_allegato", models.BooleanField(default=True)),
                (
                    "tipo_calcolo",
                    models.CharField(
                        choices=[("DOCUMENTALE", "Documentale"), ("CHILOMETRICO", "Chilometrico")],
                        default="DOCUMENTALE",
                        max_length=20,
                    ),
                ),
                ("richiede_tratta", models.BooleanField(default=False)),
                ("richiede_descrizione", models.BooleanField(default=False)),
                ("descrizione_obbligatoria", models.BooleanField(default=False)),
                ("attivo", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="figli",
                        to="note_spese.categoriaspesa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria di spesa",
                "verbose_name_plural": "Categorie di spesa",
                "ordering": ["nome"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("parent", "nome"), name="categoriaspesa_unica_per_genitore"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="centrocosto",
            constraint=models.UniqueConstraint(
                fields=("parent", "nome"), name="centrocosto_unico_per_genitore"
            ),
        ),
        migrations.AddConstraint(
            model_name="budgetcentrocosto",
            constraint=models.UniqueConstraint(
                fields=("centro_costo", "anno_scout"), name="budget_unico_per_centro_e_anno"
            ),
        ),
    ]
