# Generated by Django 6.1 on 2026-09-15 06:06

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafica", "0005_alter_capo_data_disattivazione_and_more"),
        ("note_spese", "0003_localita_comuni"),
        ("organizzazione", "0005_alter_gruppo_account_consentiti_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("data_inizio", models.DateField()),
                ("data_fine", models.DateField(blank=True, null=True)),
                ("validato", models.BooleanField(default=False)),
                ("creato_il", models.DateTimeField(auto_now_add=True)),
                (
                    "creato_da",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventi_note_spese_creati",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventi",
                "ordering": ["-data_inizio"],
            },
        ),
        migrations.CreateModel(
            name="NotaSpese",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("numero", models.CharField(blank=True, max_length=20, null=True, unique=True)),
                (
                    "incarico_altro",
                    models.CharField(
                        blank=True,
                        help_text="Obbligatorio se 'incarico' è nullo (D-50).",
                        max_length=100,
                    ),
                ),
                (
                    "stato",
                    django_fsm.FSMField(
                        choices=[
                            ("BOZZA", "Bozza"),
                            ("INVIATA", "Inviata"),
                            ("IN_VERIFICA", "In verifica"),
                            ("DA_INTEGRARE", "Da integrare"),
                            ("DA_CONFERMARE", "Da confermare"),
                            ("APPROVATA", "Approvata"),
                            ("AUTORIZZATA_RDZ", "Autorizzata RdZ"),
                            ("LIQUIDATA", "Liquidata"),
                            ("RESPINTA", "Respinta"),
                            ("ANNULLATA", "Annullata"),
                            ("DECADUTA", "Decaduta"),
                        ],
                        default="BOZZA",
                        max_length=50,
                        protected=True,
                    ),
                ),
                ("iban", models.CharField(blank=True, max_length=34)),
                ("intestatario_iban", models.CharField(blank=True, max_length=150)),
                (
                    "modalita_pagamento",
                    models.CharField(
                        blank=True,
                        choices=[("CONTANTI", "Contanti"), ("BONIFICO", "Bonifico")],
                        max_length=10,
                    ),
                ),
                ("data_pagamento", models.DateField(blank=True, null=True)),
                ("riferimento_tracciabilita", models.CharField(blank=True, max_length=100)),
                (
                    "anno_spesa",
                    models.IntegerField(
                        blank=True,
                        help_text="Derivato dalle date delle righe (D-41), ricalcolato dal service layer.",
                        null=True,
                    ),
                ),
                (
                    "anno_contabilizzazione",
                    models.IntegerField(
                        blank=True,
                        help_text="Valorizzato solo alla transizione verso LIQUIDATA (D-41). Vedi trappola in docstring.",
                        null=True,
                    ),
                ),
                (
                    "eliminata_il",
                    models.DateTimeField(
                        blank=True,
                        help_text="Soft delete (§2): mai un delete reale da qui.",
                        null=True,
                    ),
                ),
                ("creata_il", models.DateTimeField(auto_now_add=True)),
                (
                    "beneficiario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="note_spese_beneficiario",
                        to="anagrafica.capo",
                    ),
                ),
                (
                    "centro_costo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Imputato da segreteria/RdZ, non alla creazione.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="note_spese",
                        to="note_spese.centrocosto",
                    ),
                ),
                (
                    "compilatore",
                    models.ForeignKey(
                        blank=True,
                        help_text="Valorizzato solo se diverso dal beneficiario (D-36).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="note_spese_compilate",
                        to="anagrafica.capo",
                    ),
                ),
                (
                    "creata_da",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="note_spese_create",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="note_spese",
                        to="note_spese.evento",
                    ),
                ),
                (
                    "gruppo_censimento",
                    models.ForeignKey(
                        help_text="Derivato da CensimentoCapo alla creazione, congelato (D-34/D-44).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="note_spese",
                        to="organizzazione.gruppo",
                    ),
                ),
                (
                    "incarico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="note_spese",
                        to="anagrafica.incaricounita",
                    ),
                ),
                (
                    "nota_originale",
                    models.ForeignKey(
                        blank=True,
                        help_text="Clonazione (D-43) o nota di integrazione (D-40).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="derivate",
                        to="note_spese.notaspese",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota spese",
                "verbose_name_plural": "Note spese",
                "ordering": ["-creata_il"],
            },
            bases=(django_fsm.FSMModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="RigaSpesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("data", models.DateField()),
                ("descrizione", models.TextField(blank=True)),
                (
                    "tratta_testo",
                    models.CharField(
                        blank=True,
                        help_text="Tratta da/a in testo libero (Treno/Nave, Aereo, Bus/Metro/Taxi).",
                        max_length=200,
                    ),
                ),
                ("targa", models.CharField(blank=True, max_length=15)),
                (
                    "distanza_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="D-54: congelata.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("distanza_backend", models.CharField(blank=True, max_length=30)),
                ("distanza_calcolata_il", models.DateTimeField(blank=True, null=True)),
                (
                    "distanza_corretta_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Correzione manuale del verificatore (D-54).",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "importo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Inserito per le categorie documentali, cache calcolata per le chilometriche (D-45).",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("creata_il", models.DateTimeField(auto_now_add=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="righe",
                        to="note_spese.categoriaspesa",
                    ),
                ),
                (
                    "localita_arrivo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="righe_spesa_arrivo",
                        to="note_spese.localita",
                    ),
                ),
                (
                    "localita_partenza",
                    models.ForeignKey(
                        blank=True,
                        help_text="Solo categorie Auto (D-53): tratta strutturata per il calcolo distanza.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="righe_spesa_partenza",
                        to="note_spese.localita",
                    ),
                ),
                (
                    "nota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="righe",
                        to="note_spese.notaspese",
                    ),
                ),
            ],
            options={
                "verbose_name": "Riga di spesa",
                "verbose_name_plural": "Righe di spesa",
                "ordering": ["nota", "data"],
            },
        ),
        migrations.CreateModel(
            name="Allegato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file", models.FileField(upload_to="allegati_note_spese/%Y/")),
                ("caricato_il", models.DateTimeField(auto_now_add=True)),
                (
                    "caricato_da",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allegati_note_spese_caricati",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "righe",
                    models.ManyToManyField(related_name="allegati", to="note_spese.rigaspesa"),
                ),
            ],
            options={
                "verbose_name": "Allegato",
                "verbose_name_plural": "Allegati",
                "ordering": ["-caricato_il"],
            },
        ),
        migrations.CreateModel(
            name="RigaSpesaPasseggero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome_libero", models.CharField(blank=True, max_length=150)),
                (
                    "capo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="passeggeri_note_spese",
                        to="anagrafica.capo",
                    ),
                ),
                (
                    "riga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passeggeri",
                        to="note_spese.rigaspesa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Passeggero",
                "verbose_name_plural": "Passeggeri",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("capo__isnull", False),
                            models.Q(("nome_libero", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="passeggero_capo_o_nome_libero",
                    )
                ],
            },
        ),
    ]
