# Generated by Django 6.1 on 2026-09-15 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note_spese", "0004_evento_notaspese_rigaspesa_allegato_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpostazioniNoteSpese",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "autorizzazione_rdz",
                    models.CharField(
                        choices=[
                            ("NESSUNA", "Nessuna (la segreteria chiude autonomamente)"),
                            ("SINGOLA", "Singola (un RdZ qualsiasi)"),
                            ("DOPPIA", "Doppia (un RdZ maschile e uno femminile)"),
                        ],
                        default="NESSUNA",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Impostazioni Nota Spese",
                "verbose_name_plural": "Impostazioni Nota Spese",
            },
        ),
        migrations.AddField(
            model_name="notaspese",
            name="causale_respinta",
            field=models.TextField(
                blank=True,
                help_text="Motivazione del respingimento. Non specificata in una decisione D-xx per Nota Spese: obbligatoria per coerenza con lo stesso principio già applicato altrove in Catello, non un requisito testuale di questo modulo.",
            ),
        ),
        migrations.AddField(
            model_name="notaspese",
            name="rilievo_nota",
            field=models.TextField(
                blank=True, help_text="Nota testuale del verificatore sul rilievo (D-38)."
            ),
        ),
        migrations.AddField(
            model_name="notaspese",
            name="rilievo_riga",
            field=models.ForeignKey(
                blank=True,
                help_text="Riga oggetto del rilievo in DA_INTEGRARE/DA_CONFERMARE (D-38).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rilievi",
                to="note_spese.rigaspesa",
            ),
        ),
        migrations.AddField(
            model_name="rigaspesa",
            name="importo_originale",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="D-39: congelato alla prima correzione di 'importo' dopo l'invio della nota, mai più sovrascritto. Nullo se la riga non è mai stata corretta.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AutorizzazioneRdz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "genere",
                    models.CharField(choices=[("M", "Maschile"), ("F", "Femminile")], max_length=1),
                ),
                ("creata_il", models.DateTimeField(auto_now_add=True)),
                (
                    "nota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autorizzazioni_rdz",
                        to="note_spese.notaspese",
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="autorizzazioni_rdz_firmate",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Autorizzazione RdZ",
                "verbose_name_plural": "Autorizzazioni RdZ",
                "ordering": ["-creata_il"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("nota", "genere"), name="autorizzazione_rdz_unica_per_genere"
                    )
                ],
            },
        ),
    ]
