# Generated by Django 6.1 on 2026-09-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note_spese", "0005_impostazioninotespese_notaspese_causale_respinta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notaspese",
            name="rilievo_il",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp del rilievo: un nuovo allegato successivo sblocca DA_INTEGRARE (D-38).",
                null=True,
            ),
        ),
    ]
