# Generated by Django 6.1 on 2026-09-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note_spese", "0006_notaspese_rilievo_il"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoriaspesa",
            name="sottotipo_chilometrico",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ANDATA_RITORNO", "Auto andata e ritorno"),
                    ("ALTRO", "Auto altri spostamenti"),
                ],
                help_text="Solo per tipo_calcolo=CHILOMETRICO (D-53): distingue andata/ritorno da altri spostamenti.",
                max_length=20,
            ),
        ),
    ]
