# Generated by Django 6.1 on 2026-09-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note_spese", "0008_backfill_sottotipo_chilometrico"),
    ]

    operations = [
        migrations.CreateModel(
            name="TariffaChilometrica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "fascia",
                    models.CharField(
                        choices=[
                            ("TRE_O_PIU", "3 o più passeggeri"),
                            ("BREVE", "1 o 2 passeggeri, fino a 200 km"),
                            ("LUNGA", "1 o 2 passeggeri, oltre 200 km"),
                        ],
                        max_length=20,
                    ),
                ),
                ("importo_km", models.DecimalField(decimal_places=2, max_digits=5)),
                ("valida_dal", models.DateField()),
                (
                    "valida_al",
                    models.DateField(blank=True, help_text="Vuoto se ancora in vigore.", null=True),
                ),
            ],
            options={
                "verbose_name": "Tariffa chilometrica",
                "verbose_name_plural": "Tariffe chilometriche",
                "ordering": ["fascia", "-valida_dal"],
            },
        ),
    ]
