# Generated by Django 6.1 on 2026-09-16 06:41

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note_spese", "0009_tariffachilometrica"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allegato",
            name="file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="allegati_note_spese/%Y/",
            ),
        ),
    ]
