# Generated by Django 6.1 on 2026-09-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note_spese", "0010_alter_allegato_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="impostazioninotespese",
            name="report_destinatari_admin",
            field=models.BooleanField(default=False, verbose_name="Admin"),
        ),
        migrations.AddField(
            model_name="impostazioninotespese",
            name="report_destinatari_rdz",
            field=models.BooleanField(default=False, verbose_name="RdZ"),
        ),
        migrations.AddField(
            model_name="impostazioninotespese",
            name="report_destinatari_segreteria",
            field=models.BooleanField(default=False, verbose_name="Segreteria"),
        ),
        migrations.AddField(
            model_name="impostazioninotespese",
            name="report_giorni_settimana",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Giorni della settimana in cui inviare il report ai gestori. Vuoto: report disattivato.",
            ),
        ),
        migrations.AddField(
            model_name="impostazioninotespese",
            name="report_orario",
            field=models.TimeField(
                blank=True, help_text="Orario di invio nei giorni selezionati sopra.", null=True
            ),
        ),
        migrations.AddField(
            model_name="impostazioninotespese",
            name="report_ultimo_invio",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
