# Generated by Django 6.1 on 2026-09-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note_spese", "0011_impostazioninotespese_report_destinatari_admin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notaspese",
            name="inviata_il",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Data di presentazione (D-67), valorizzata da invia_nota() insieme a numero/anno_spesa.",
                null=True,
            ),
        ),
    ]
