# Generated by Django 6.1 on 2026-09-24 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note_spese", "0012_notaspese_inviata_il"),
    ]

    operations = [
        migrations.CreateModel(
            name="CopiaDrive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("IN_ATTESA", "In attesa"),
                            ("COPIATO", "Copiato"),
                            ("FALLITO", "Fallito"),
                        ],
                        default="IN_ATTESA",
                        max_length=10,
                    ),
                ),
                ("tentativi", models.PositiveSmallIntegerField(default=0)),
                ("ultimo_errore", models.TextField(blank=True)),
                ("drive_file_id", models.CharField(blank=True, max_length=100)),
                ("creata_il", models.DateTimeField(auto_now_add=True)),
                ("aggiornata_il", models.DateTimeField(auto_now=True)),
                (
                    "allegato",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nullo: il file da copiare è il PDF della nota stessa, generato al volo.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copie_drive",
                        to="note_spese.allegato",
                    ),
                ),
                (
                    "nota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copie_drive",
                        to="note_spese.notaspese",
                    ),
                ),
            ],
            options={
                "verbose_name": "Copia su Drive",
                "verbose_name_plural": "Copie su Drive",
                "ordering": ["-creata_il"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("allegato__isnull", False)),
                        fields=("allegato",),
                        name="una_copia_drive_per_allegato",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("allegato__isnull", True)),
                        fields=("nota",),
                        name="una_copia_drive_del_pdf_per_nota",
                    ),
                ],
            },
        ),
    ]
