# Generated by Django 6.1 on 2026-09-26 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafica", "0005_alter_capo_data_disattivazione_and_more"),
        ("note_spese", "0013_copiadrive"),
        ("organizzazione", "0005_alter_gruppo_account_consentiti_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriaspesa",
            name="sottotipo_chilometrico",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ANDATA_RITORNO", "Auto andata e ritorno"),
                    ("ALTRO", "Auto altri spostamenti"),
                ],
                help_text="Solo per tipo_calcolo=CHILOMETRICO: distingue andata/ritorno da altri spostamenti.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notaspese",
            name="anno_contabilizzazione",
            field=models.IntegerField(
                blank=True,
                help_text="Valorizzato solo alla transizione verso LIQUIDATA. Vedi trappola in docstring.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notaspese",
            name="anno_spesa",
            field=models.IntegerField(
                blank=True,
                help_text="Derivato dalle date delle righe, ricalcolato dal service layer.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notaspese",
            name="causale_respinta",
            field=models.TextField(
                blank=True,
                help_text="Motivazione del respingimento. Non specificata in una decisione dedicata per Nota Spese: obbligatoria per coerenza con lo stesso principio già applicato altrove in Catello, non un requisito testuale di questo modulo.",
            ),
        ),
        migrations.AlterField(
            model_name="notaspese",
            name="compilatore",
            field=models.ForeignKey(
                blank=True,
                help_text="Valorizzato solo se diverso dal beneficiario.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="note_spese_compilate",
                to="anagrafica.capo",
            ),
        ),
        migrations.AlterField(
            model_name="notaspese",
            name="gruppo_censimento",
            field=models.ForeignKey(
                help_text="Derivato da CensimentoCapo alla creazione, congelato.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="note_spese",
                to="organizzazione.gruppo",
            ),
        ),
        migrations.AlterField(
            model_name="notaspese",
            name="incarico_altro",
            field=models.CharField(
                blank=True, help_text="Obbligatorio se 'incarico' è nullo.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="notaspese",
            name="inviata_il",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Data di presentazione, valorizzata da invia_nota() insieme a numero/anno_spesa.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notaspese",
            name="nota_originale",
            field=models.ForeignKey(
                blank=True,
                help_text="Clonazione o nota di integrazione.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="derivate",
                to="note_spese.notaspese",
            ),
        ),
        migrations.AlterField(
            model_name="notaspese",
            name="rilievo_il",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp del rilievo: un nuovo allegato successivo sblocca DA_INTEGRARE.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notaspese",
            name="rilievo_nota",
            field=models.TextField(
                blank=True, help_text="Nota testuale del verificatore sul rilievo."
            ),
        ),
        migrations.AlterField(
            model_name="notaspese",
            name="rilievo_riga",
            field=models.ForeignKey(
                blank=True,
                help_text="Riga oggetto del rilievo in DA_INTEGRARE/DA_CONFERMARE.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rilievi",
                to="note_spese.rigaspesa",
            ),
        ),
        migrations.AlterField(
            model_name="rigaspesa",
            name="distanza_corretta_km",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Correzione manuale del verificatore.",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rigaspesa",
            name="distanza_km",
            field=models.DecimalField(
                blank=True, decimal_places=1, help_text="Congelata.", max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="rigaspesa",
            name="importo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Inserito per le categorie documentali, cache calcolata per le chilometriche.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rigaspesa",
            name="importo_originale",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Congelato alla prima correzione di 'importo' dopo l'invio della nota, mai più sovrascritto. Nullo se la riga non è mai stata corretta.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rigaspesa",
            name="localita_partenza",
            field=models.ForeignKey(
                blank=True,
                help_text="Solo categorie Auto: tratta strutturata per il calcolo distanza.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="righe_spesa_partenza",
                to="note_spese.localita",
            ),
        ),
    ]
