# Generated by Django 6.1 on 2026-08-20 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizzazione", "0002_seed_e9001"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Capo",
            fields=[
                (
                    "codice_socio",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cognome", models.CharField(max_length=100)),
                ("sesso", models.CharField(blank=True, max_length=1)),
                ("data_nascita", models.DateField(blank=True, null=True)),
                ("comune_nascita", models.CharField(blank=True, max_length=100)),
                ("codice_fiscale", models.CharField(blank=True, max_length=16)),
                ("nazionalita", models.CharField(blank=True, max_length=100)),
                ("indirizzo", models.CharField(blank=True, max_length=200)),
                ("civico", models.CharField(blank=True, max_length=10)),
                ("comune_residenza", models.CharField(blank=True, max_length=100)),
                ("provincia_residenza", models.CharField(blank=True, max_length=5)),
                ("cap", models.CharField(blank=True, max_length=10)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("cellulare", models.CharField(blank=True, max_length=30)),
                ("professione", models.CharField(blank=True, max_length=200)),
                ("attivo", models.BooleanField(default=True)),
                (
                    "data_disattivazione",
                    models.DateField(
                        blank=True,
                        help_text="Valorizzata alla disattivazione, azzerata alla riattivazione (D-22).",
                        null=True,
                    ),
                ),
                (
                    "utente",
                    models.OneToOneField(
                        blank=True,
                        help_text="Account personale collegato. Mai valorizzato dall'import CSV.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="capo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Capo",
                "verbose_name_plural": "Capi",
                "ordering": ["cognome", "nome"],
            },
        ),
        migrations.CreateModel(
            name="ImportazioneCSV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file", models.FileField(upload_to="import_csv/%Y/")),
                (
                    "anno_scout",
                    models.IntegerField(
                        help_text="Letto dal CSV (colonna ANNO SCOUT), non scelto."
                    ),
                ),
                ("conteggi", models.JSONField(default=dict)),
                ("anomalie", models.JSONField(default=list)),
                ("eseguita_il", models.DateTimeField(auto_now_add=True)),
                (
                    "capi_disattivati",
                    models.ManyToManyField(
                        blank=True, related_name="disattivazioni_import", to="anagrafica.capo"
                    ),
                ),
                (
                    "capi_riattivati",
                    models.ManyToManyField(
                        blank=True, related_name="riattivazioni_import", to="anagrafica.capo"
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="importazioni_csv",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Importazione CSV",
                "verbose_name_plural": "Importazioni CSV",
                "ordering": ["-eseguita_il"],
            },
        ),
        migrations.CreateModel(
            name="TrasferimentoCapo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("anno_scout", models.IntegerField()),
                ("rilevato_il", models.DateTimeField(auto_now_add=True)),
                (
                    "origine",
                    models.CharField(
                        choices=[
                            ("IMPORT_CSV", "Import CSV anagrafico"),
                            ("IMPORT_AUTORIZZAZIONI", "Import autorizzazioni"),
                            ("MANUALE", "Manuale"),
                        ],
                        default="IMPORT_CSV",
                        max_length=25,
                    ),
                ),
                (
                    "capo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trasferimenti",
                        to="anagrafica.capo",
                    ),
                ),
                (
                    "gruppo_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trasferimenti_in_entrata",
                        to="organizzazione.gruppo",
                    ),
                ),
                (
                    "gruppo_origine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trasferimenti_in_uscita",
                        to="organizzazione.gruppo",
                    ),
                ),
                (
                    "importazione",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trasferimenti",
                        to="anagrafica.importazionecsv",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trasferimento capo",
                "verbose_name_plural": "Trasferimenti capi",
                "ordering": ["-rilevato_il"],
            },
        ),
        migrations.CreateModel(
            name="CensimentoCapo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("anno_scout", models.IntegerField()),
                (
                    "branca",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LC", "Lupetti/Coccinelle"),
                            ("EG", "Esploratori/Guide"),
                            ("RS", "Rover/Scolte"),
                            ("SG", "Supporto al gruppo"),
                            ("AE", "Assistente ecclesiastico"),
                        ],
                        default="",
                        max_length=5,
                    ),
                ),
                ("is_capogruppo", models.BooleanField(default=False)),
                (
                    "a_disposizione",
                    models.BooleanField(
                        default=True,
                        help_text="Derivato: nessun incarico attivo nell'anno (D-31). Ricalcolato da zero a ogni import.",
                    ),
                ),
                ("livello_foca", models.IntegerField(blank=True, null=True)),
                ("comunita_socio", models.CharField(blank=True, max_length=100)),
                ("status_socio", models.CharField(blank=True, max_length=100)),
                ("ingresso_coca", models.CharField(blank=True, max_length=20)),
                (
                    "capo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="censimenti",
                        to="anagrafica.capo",
                    ),
                ),
                (
                    "gruppo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="censimenti",
                        to="organizzazione.gruppo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Censimento capo",
                "verbose_name_plural": "Censimenti capi",
                "ordering": ["-anno_scout", "capo"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("capo", "anno_scout"), name="uniq_censimento_capo_anno"
                    )
                ],
            },
        ),
    ]
