# Generated by Django 6.1 on 2026-08-20 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafica", "0001_initial"),
        ("organizzazione", "0002_seed_e9001"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="censimentocapo",
            name="branca",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LC", "Lupetti/Coccinelle"),
                    ("EG", "Esploratori/Guide"),
                    ("RS", "Rover/Scolte"),
                    ("SG", "Supporto al gruppo"),
                    ("AE", "Assistente ecclesiastico"),
                    ("NON_ASSEGNATA", "Non assegnata"),
                ],
                default="",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="ImportazioneAutorizzazioni",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("anno_scout", models.IntegerField()),
                ("conteggi", models.JSONField(default=dict)),
                ("anomalie", models.JSONField(default=list)),
                ("eseguita_il", models.DateTimeField(auto_now_add=True)),
                (
                    "utente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="importazioni_autorizzazioni",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Importazione autorizzazioni",
                "verbose_name_plural": "Importazioni autorizzazioni",
                "ordering": ["-eseguita_il"],
            },
        ),
        migrations.CreateModel(
            name="FileAutorizzazionePDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file", models.FileField(upload_to="import_autorizzazioni/%Y/")),
                ("nome_file_originale", models.CharField(blank=True, max_length=255)),
                ("data_aggiornamento", models.DateField()),
                (
                    "gruppo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="file_autorizzazione",
                        to="organizzazione.gruppo",
                    ),
                ),
                (
                    "importazione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_pdf",
                        to="anagrafica.importazioneautorizzazioni",
                    ),
                ),
            ],
            options={
                "verbose_name": "File autorizzazione PDF",
                "verbose_name_plural": "File autorizzazione PDF",
                "ordering": ["-data_aggiornamento"],
            },
        ),
        migrations.CreateModel(
            name="Pattuglia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "branca",
                    models.CharField(
                        choices=[
                            ("LC", "Lupetti/Coccinelle"),
                            ("EG", "Esploratori/Guide"),
                            ("RS", "Rover/Scolte"),
                        ],
                        max_length=5,
                    ),
                ),
                ("anno_scout", models.IntegerField()),
            ],
            options={
                "verbose_name": "Pattuglia",
                "verbose_name_plural": "Pattuglie",
                "ordering": ["-anno_scout", "branca"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("branca", "anno_scout"), name="uniq_pattuglia_branca_anno"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IncaricoUnita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("anno_scout", models.IntegerField()),
                ("codice_unita", models.CharField(max_length=10)),
                ("nome_unita", models.CharField(blank=True, max_length=100)),
                (
                    "branca",
                    models.CharField(
                        choices=[
                            ("LC", "Lupetti/Coccinelle"),
                            ("EG", "Esploratori/Guide"),
                            ("RS", "Rover/Scolte"),
                            ("ADULTI", "Adulti (Comunità Capi)"),
                            ("SCONOSCIUTA", "Sconosciuta"),
                        ],
                        max_length=15,
                    ),
                ),
                ("genere_unita", models.CharField(blank=True, max_length=10)),
                (
                    "funzione",
                    models.CharField(
                        choices=[
                            ("CAPO_UNITA", "Capo unità"),
                            ("AIUTO_CAPO_UNITA", "Aiuto capo unità"),
                            ("CAPO_GRUPPO", "Capo gruppo"),
                            ("AE_GRUPPO", "Assistente ecclesiastico di gruppo"),
                            ("AE_UNITA", "Assistente ecclesiastico di unità"),
                            ("SUPPORTO_GRUPPO", "Servizio di supporto al gruppo"),
                            (
                                "SUPPORTO_AZIONE_EDUCATIVA",
                                "Servizio di supporto all'azione educativa",
                            ),
                            ("MAESTRO_NOVIZI", "Maestro dei novizi"),
                        ],
                        max_length=30,
                    ),
                ),
                ("livello_foca", models.IntegerField(blank=True, null=True)),
                (
                    "origine",
                    models.CharField(
                        choices=[("IMPORT", "Import autorizzazione"), ("MANUALE", "Manuale")],
                        max_length=10,
                    ),
                ),
                (
                    "cessato_il",
                    models.DateTimeField(
                        blank=True, help_text="Attivo se nullo (D-32). Mai un delete.", null=True
                    ),
                ),
                ("creato_il", models.DateTimeField(auto_now_add=True)),
                (
                    "assegnato_da",
                    models.ForeignKey(
                        blank=True,
                        help_text="Valorizzato solo per origine MANUALE.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incarichi_assegnati",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "capo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incarichi",
                        to="anagrafica.capo",
                    ),
                ),
                (
                    "gruppo_servizio",
                    models.ForeignKey(
                        help_text="Gruppo la cui autorizzazione dichiara l'incarico (D-34).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incarichi_unita",
                        to="organizzazione.gruppo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incarico in unità",
                "verbose_name_plural": "Incarichi in unità",
                "ordering": ["-anno_scout", "capo"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("cessato_il__isnull", True)),
                        fields=(
                            "capo",
                            "anno_scout",
                            "gruppo_servizio",
                            "codice_unita",
                            "funzione",
                        ),
                        name="uniq_incarico_unita_attivo",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MembroPattuglia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "capo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pattuglie",
                        to="anagrafica.capo",
                    ),
                ),
                (
                    "pattuglia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membri",
                        to="anagrafica.pattuglia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membro pattuglia",
                "verbose_name_plural": "Membri pattuglia",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pattuglia", "capo"), name="uniq_membro_pattuglia"
                    )
                ],
            },
        ),
    ]
