# Generated by Django 6.1 on 2026-08-21 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafica", "0002_alter_censimentocapo_branca_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EsportazioneAnagrafica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("anno_scout", models.IntegerField()),
                ("filtri", models.JSONField(default=dict)),
                (
                    "profilo_colonne",
                    models.CharField(
                        choices=[("MINIMO", "Minimo"), ("ESTESO", "Esteso")], max_length=10
                    ),
                ),
                ("numero_righe", models.IntegerField()),
                (
                    "numero_capi",
                    models.IntegerField(
                        help_text="Capi distinti, non righe: un capo con più incarichi genera più righe (D-23)."
                    ),
                ),
                ("eseguita_il", models.DateTimeField(auto_now_add=True)),
                (
                    "utente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="esportazioni_anagrafica",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Esportazione anagrafica",
                "verbose_name_plural": "Esportazioni anagrafica",
                "ordering": ["-eseguita_il"],
            },
        ),
    ]
