# Generated by Django 6.1 on 2026-08-21 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafica", "0003_esportazioneanagrafica"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecapitoCapo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("EMAIL", "Email"), ("CELLULARE", "Cellulare")], max_length=10
                    ),
                ),
                ("valore", models.CharField(max_length=254)),
                (
                    "capo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recapiti",
                        to="anagrafica.capo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recapito capo",
                "verbose_name_plural": "Recapiti capi",
                "ordering": ["capo", "tipo", "valore"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("capo", "tipo", "valore"), name="uniq_recapito_capo"
                    )
                ],
            },
        ),
    ]
