# Generated by Django 6.1 on 2026-09-06 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafica", "0004_recapitocapo"),
        ("organizzazione", "0005_alter_gruppo_account_consentiti_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capo",
            name="data_disattivazione",
            field=models.DateField(
                blank=True,
                help_text="Valorizzata alla disattivazione, azzerata alla riattivazione.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="censimentocapo",
            name="a_disposizione",
            field=models.BooleanField(
                default=True,
                help_text="Derivato: nessun incarico attivo nell'anno. Ricalcolato da zero a ogni import.",
            ),
        ),
        migrations.AlterField(
            model_name="esportazioneanagrafica",
            name="numero_capi",
            field=models.IntegerField(
                help_text="Capi distinti, non righe: un capo con più incarichi genera più righe."
            ),
        ),
        migrations.AlterField(
            model_name="incaricounita",
            name="cessato_il",
            field=models.DateTimeField(
                blank=True, help_text="Attivo se nullo. Mai un delete.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="incaricounita",
            name="gruppo_servizio",
            field=models.ForeignKey(
                help_text="Gruppo la cui autorizzazione dichiara l'incarico.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incarichi_unita",
                to="organizzazione.gruppo",
            ),
        ),
    ]
